export enum TagNamesEnum {
    // 4.1 The document element https://html.spec.whatwg.org/multipage/semantics.html#the-root-element
    HTML = "html",
    // 4.2 Document metadata https://html.spec.whatwg.org/multipage/semantics.html#document-metadata
    HEAD = "head",
    TITLE = "title",
    BASE = "base",
    LINK = "link",
    META = "meta",
    STYLE = "style",
    // 4.3 Sections https://html.spec.whatwg.org/multipage/sections.html#sections
    BODY = "body",
    ARTICLE = "article",
    SECTION = "section",
    NAV = "nav",
    ASIDE = "aside",
    H1 = "h1",
    H2 = "h2",
    H3 = "h3",
    H4 = "h4",
    H5 = "h5",
    H6 = "h6",
    HGROUP = "hgroup",
    HEADER = "header",
    FOOTER = "footer",
    ADDRESS = "address",
    // 4.4 Grouping content https://html.spec.whatwg.org/multipage/grouping-content.html#grouping-content
    P = "p",
    HR = "hr",
    PRE = "pre",
    BLOCKQUOTE = "blockquote",
    OL = "ol",
    UL = "ul",
    MENU = "menu",
    LI = "li",
    DL = "dl",
    DT = "dt",
    DD = "dd",
    FIGURE = "figure",
    FIGCAPTION = "figcaption",
    MAIN = "main",
    DIV = "div",
    // 4.5 Text-level semantics https://html.spec.whatwg.org/multipage/text-level-semantics.html#text-level-semantics
    A = "a",
    EM = "em",
    STRONG = "strong",
    S = "s",
    CITE = "cite",
    Q = "q",
    DFN = "dfn",
    ABBR = "abbr",
    RUBY = "ruby",
    RT = "rt",
    RP = "rp",
    DATA = "data",
    TIME = "time",
    CODE = "code",
    VAR = "var",
    SAMP = "samp",
    KBD = "kbd",
    SUB = "sub",
    SUP = "sup",
    I = "i",
    B = "b",
    U = "u",
    MARK = "mark",
    BDI = "bdi",
    BDO = "bdo",
    SPAN = "span",
    BR = "br",
    WBR = "wbr",
    // 4.6 Links https://html.spec.whatwg.org/multipage/links.html#links
    // == Links has a and area element description, but not defined those elements. ==
    // 4.7 Edits https://html.spec.whatwg.org/multipage/edits.html#edits
    INS = "ins",
    DEL = "del",
    // 4.8 Embedded content https://html.spec.whatwg.org/multipage/embedded-content.html#embedded-content
    PICTURE = "picture",
    SOURCE = "source",
    IMG = "img",
    IFRAME = "iframe",
    EMBED = "embed",
    OBJECT = "object",
    PARAM = "param",
    VIDEO = "video",
    AUDIO = "audio",
    TRACK = "track",
    MAP = "map",
    AREA = "area",
    // 4.9 Tabular data https://html.spec.whatwg.org/multipage/tables.html#tables
    TABLE = "table",
    CAPTION = "caption",
    COLGROUP = "colgroup",
    COL = "col",
    TBODY = "tbody",
    THEAD = "thead",
    TFOOT = "tfoot",
    TR = "tr",
    TD = "td",
    TH = "th",
    // 4.10 Forms https://html.spec.whatwg.org/multipage/forms.html#forms
    FORM = "form",
    LABEL = "label",
    INPUT = "input",
    BUTTON = "button",
    SELECT = "select",
    DATALIST = "datalist",
    OPTGROUP = "optgroup",
    OPTION = "option",
    TEXTAREA = "textarea",
    OUTPUT = "output",
    PROGRESS = "progress",
    METER = "meter",
    FIELDSET = "fieldset",
    LEGEND = "legend",
    // 4.11 Interactive elements https://html.spec.whatwg.org/multipage/interactive-elements.html#interactive-elements
    DETAILS = "details",
    SUMMARY = "summary",
    DIALOG = "dialog",
    // 4.12 Scripting https://html.spec.whatwg.org/multipage/scripting.html#scripting-3
    SCRIPT = "script",
    NOSCRIPT = "noscript",
    TEMPLATE = "template",
    SLOT = "slot",
    CANVAS = "canvas"
}
